client_config_backend: settings
client_config:
  client_id: 667625875655-ksrbgedjnd0gt6tbcnli1p8u93n4g32p.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install